#CONFIG_FLASH_SIZE=131072
#CONFIG_FLASH_BASE_ADDRESS=0
#CONFIG_MCUBOOT_LOG_LEVEL_DBG=y
CONFIG_USE_DT_CODE_PARTITION=n
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_FLASH_BASE_ADDRESS=0xC0000
CONFIG_FLASH_LOAD_OFFSET=0
CONFIG_UART_LOG_LEVEL_DBG=y
CONFIG_MCUBOOT_EXTRA_IMGTOOL_ARGS="--pad --pad-header --header-size 0x200 --confirm"
CONFIG_ESPIHUB_LOG_LEVEL=4
#CONFIG_DEBUG=y
#CONFIG_OUTPUT_DISASSEMBLY=y
#CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
