#CONFIG_FLASH_SIZE=131072
#CONFIG_FLASH_BASE_ADDRESS=0xF8000
#CONFIG_FLASH_BASE_ADDRESS=0
CONFIG_MCUBOOT_LOG_LEVEL_DBG=y
CONFIG_FLASH_BASE_ADDRESS=0x100000
CONFIG_UART_LOG_LEVEL_DBG=y
#CONFIG_BOOT_DIRECT_XIP=y
#CONFIG_BOOT_DIRECT_XIP_REVERT=y
#CONFIG_DEBUG=y
CONFIG_OUTPUT_DISASSEMBLY=y
CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
