manifest:
  version: 0.7

  defaults:
    remote: silicom-ltd
  remotes:
    - name: silicom-ltd
      url-base: https://github.com/silicom-ltd
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      repo-path: zephyr-silicom
      revision: cbe2a3e5817197f75d11ce5163e447429686db4b
      path: zephyr
      west-commands: scripts/west-commands.yml
    - name: hal_microchip
      remote: upstream
      revision: 5d079f1683a00b801373bbbbf5d181d4e33b30d5
      path: modules/hal/microchip
      groups:
        - hal
    - name: cmsis
      remote: upstream
      revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
      path: modules/hal/cmsis
      groups:
        - hal
    - name: mcuboot
      remote: upstream
      revision: a4eda30f5b0cfd0cf15512be9dcd559239dbfc91
      path: bootloader/mcuboot
  self:
    path: ecfw-zephyr
