manifest:
  version: 0.7

  defaults:
    remote: silicom-ltd
  remotes:
    - name: silicom-ltd
      url-base: https://github.com/silicom-ltd
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: microchip
      url-base: https://github.com/MicrochipTech
  projects:
    - name: zephyr
      repo-path: zephyr-silicom
      revision: 988faf3c4c31fea1d04b7d4caa42f6c4031465b8
      path: zephyr
      west-commands: scripts/west-commands.yml
    - name: hal_microchip
      remote: upstream
      revision: 5d079f1683a00b801373bbbbf5d181d4e33b30d5
      path: modules/hal/microchip
      groups:
        - hal
    - name: cmsis
      remote: upstream
      revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
      path: modules/hal/cmsis
      groups:
        - hal
    - name: mcuboot
      remote: upstream
      revision: a4eda30f5b0cfd0cf15512be9dcd559239dbfc91
      path: bootloader/mcuboot
    - name: CPGZephyrDocs
      remote: microchip
      revision: de150196c8ae5bf00f47c9e2f4cccfafee5844ab
      path: tools
  self:
    path: ecfw-zephyr
